export const skillsTechnologies = [
    'JavaScript (ES6+)',
    'Typescript',
    'React.js',
    'Vue.js',
    'Angular',
    'Node.js',
    'Express.js',
    'Next.js',
    'HTML5',
    'CSS3',
    'Sass',
    'SCSS',
    'LESS',
    'Tailwind CSS',
    'Bootstrap',
    'Material-UI',
    'Git',
    'Redux',
    'Redux Toolkit',
    'RTK Query',
    'REST API',
    'GraphQL',
    'Socket.io',
    'CI/CD',
    'Jest',
    'React Testing Library',
    'Mocha',
    'Chai',
    'Python',
    'Django',
    'Flask',
    'NumPy',
    'Pandas',
    'Matplotlib',
    'SciPy',
    'TensorFlow',
    'Keras',
    'PyTorch',
    'NLTK',
    'Scikit-learn',
    'PHP',
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'WordPress',
    'Drupal',
    'Magento',
    'MySQL',
    'PostgreSQL',
    'MongoDB',
    'AWS',
    'Amazon S3',
    'Amazon EC2',
    'Amazon RDS',
    'Amazon DynamoDB',
    'Amazon Aurora',
    'Vue.js',
    'Vuex',
    'Vue Router',
    'Nuxt.js',
    'Angular',
    'Angular CLI',
    'Angular Material',
    'RxJS',
    'MySQL',
    'MongoDB',
    'Firebase',
    'AWS RDS',
    'AWS DynamoDB',
    'AWS S3',
    'AWS Lambda',
    'Docker',
    'Docker Compose',
    'Objection',
    'WebRTC',
    'TypeORM',
    'Scrum',
    'Agile',
    'SOLID',
    'SRP',
    'LSP',
    'ISP',
    'Fastify',
    'Knex',
    'Storybook',
    'Google Fit API',
    'Strava API',
    'OpenAI API',
    'Stripe API',
    'Google OAuth',
    'Sendgrid',
    'GitHub Actions',
    'ect.',
    'end ect.'
];
